pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r saucedemo-playwright-suite/requirements.txt'
            }
        }
        stage('Install Browsers') {
            steps {
                sh 'python3 -m playwright install chromium'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'cd saucedemo-playwright-suite && python3 -m pytest tests/ -v --alluredir=allure-results'
            }
        }
    }
    post {
        always {
            echo 'Pipeline complete!'
        }
        success {
            echo 'All tests passed!'
        }
        failure {
            echo 'Tests failed!'
        }
    }
}
